description = "Gemini Code セッションの振り返りを行う"

prompt = """
Gemini Code のセッションで行ったやりとり、タスクを振り返って指定したディレクトリに Markdown ファイルに出力するカスタムスラッシュコマンドです。

作成するファイルのパスおよび名前は ~/tasks/{YEAR}/{MONTH}/{DAY}/{TASK_NAME}.reflection.md としてください。
ファイルパス・ファイル名は下記を参考に動的に選択してください。

- {YEAR}: コマンド実行時の年で置き換える
- {MONTH}: コマンド実行時の月で置き換える
- {DAY}: コマンド実行時の日で置き換える
- {TASK_NAME}: セッションでおこなったやりとり・タスクの概要を元に一言で置き換える。

振り返りは YWT のフォーマットで簡潔に整理してください。

## Format

YWT のフォーマットは具体的には下記の通りです。

- Y (やったこと): 実行したこと、経験したことを客観的に書き出します。成功体験だけでなく、想定外の出来事や課題も含みます。
- W (わかったこと): 「Y」で書き出した事実をもとに、自分が何を感じ、何を気づいたかを深掘りします。一人ひとりの経験や価値観に基づく気づきが重要です。
- T (次にやること): 「W」で得た気づきを活かし、今後の具体的な行動や計画を立てます。できたことの継続や、課題の改善策などを具体的に考えます。

## Purpose

このスラッシュコマンドは、 Gemini Code を通じて実施したタスクを振り返りすることができるようにすることを目的とします。

このスラッシュコマンドで作成したファイルの用途は下記を想定しています。

- 週次・月次など一定の期間でやったことを振り返る
- 目標の達成度や振り返りを効率的に行い、生成 AI と改善策についてディスカッションする
"""
